version: '3.7'
services:
  get-email:
    build:
      context: ./get-email
      dockerfile: Dockerfile
    ports:
      - 443:443
  send-email:
    build:
      context: ./send-email
      dockerfile: Dockerfile
    ports:
      - 8086:80